= Releasing

Releases are published from the community fork under the `io.plurima.parallelconsumer` Maven group.

- Verify that `CHANGELOG.adoc`, `README.adoc`, and `src/docs/README_TEMPLATE.adoc` are up-to-date with the release.
- Verify the working tree is clean.
- Set the release version, for example:
+
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home ./mvnw --batch-mode versions:set -DnewVersion=0.5.4.0 -DprocessAllModules=true -DgenerateBackupPoms=false
```
- Build locally:
+
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home ./mvnw --batch-mode -DskipTests package
```
- Publish to Maven Central:
+
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home ./mvnw --batch-mode clean deploy -Pmaven-central -DperformRelease=true -DskipTests
```
- Wait for Central Portal validation and publish.
- Verify the release is available on Maven Central:
+
```
https://repo1.maven.org/maven2/io/plurima/parallelconsumer/parallel-consumer-parent/
https://repo1.maven.org/maven2/io/plurima/parallelconsumer/parallel-consumer-core/
```
- Tag the release and create the GitHub release.
- Set the next development version, for example:
+
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home ./mvnw --batch-mode versions:set -DnewVersion=0.5.4.1-SNAPSHOT -DprocessAllModules=true -DgenerateBackupPoms=false
```

== Snapshots

Snapshots are deployed to Sonatype Central snapshots:

```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home ./mvnw --batch-mode -DskipTests deploy
```

Verify snapshot metadata directly:

```
https://central.sonatype.com/repository/maven-snapshots/io/plurima/parallelconsumer/parallel-consumer-core/0.5.4.0-SNAPSHOT/maven-metadata.xml
```

== Troubleshooting

There seems to be a bug somewhere in Maven plugins or just timeout getting caught when deploying to sonatype - after actual deployment is done - logs like this:
```
[INFO]  * Upload of locally staged artifacts finished.04:49
[INFO]  * Closing staging repository with ID "ioconfluent".04:49
Waiting for operation to complete...04:49
..................................06:30
[INFO] Remote staged 1 repositories, finished with success.06:30
[INFO] Remote staging repositories are being released...06:30
Waiting for operation to complete...06:30
.......Oct 21, 2024 1:04:39 PM com.sun.jersey.api.client.ClientResponse getEntity07:22
SEVERE: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found07:22
Oct 21, 2024 1:04:39 PM com.sun.jersey.api.client.ClientResponse getEntity
```
Shows up as promotion failed - but as you can see the actual deployment was successful.

In case of actual upload failure / build failure of the tagged branch - the tag might need to be reverted - which is locked by devprod and github task has to be ran to revert the Tag.

`delete-github-tag` in https://semaphore.ci.confluent.io/projects/github-tasks/schedulers.

This will delete the tag (actually it will rename the tag to TAG-DELETED - i.e. 0.5.3.3-deleted) so that whatever build issue there is can be remedied (with revert / new PRs to Master branch) and when ready to do a release again - you can follow this process again.
